check-updates: true
blocked-message: "§cYou are not allowed to redeem that voucher here."
blocked-regions:
 spawnregion:
 - blockedvoucherone
 - blockedvouchertwo
blocked-console: "&6BLOCKED: %player% tried to redeem %voucher% in %region%."